### PR TITLE
Update pesapal-ipn-listener.php

### PR DESCRIPTION
**Pull request by johnwaweru**
Closes https://github.com/itskingori/pesapal-php/issues/1.

### CODE REVIEW

**Comment by itskingori** [comment]
@johnwaweru thanks for this! Seeing this now 🙈

**Comment by itskingori** [comment]
Closes https://github.com/itskingori/pesapal-php/issues/1.

**Comment by itskingori** [comment]
@johnwaweru closed instead of merging. 🤕

**Comment by johnini** [comment]
No biggie. Created another PR.

**Pull request closed without merging**
